/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.espinas.fhir;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

class ApplicationTest {

    @Test
    @DisplayName("app greeting Test")
    void appHasAGreeting() {
//        Application classUnderTest = new Application();
//        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
