/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.espinas.fhir;

import org.springframework.boot.test.context.SpringBootTest;

@SpringBootTest
class ApplicationTest {
}