server:
  port: 8888

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  data:
    mongodb:
      database: mongo
      port: 27017
      uri: mongodb://localhost:27017/mongo

fhir:
  profile:
    version: 1.1.4

---

spring:
  profiles:
    active: local

---

spring:
  profiles:
    active: dev

---

spring:
  profiles:
    active: prod
