/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.jhkang;

import org.junit.jupiter.api.Test;

class ApplicationTest {
    @Test void appHasAGreeting() {
//        Application classUnderTest = new Application();
//        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
